Makefile: fix building with recent clang
Properly set C++ language with recent clang versions, to address build
problems caused by the compiler assuming a C project.

This fixes errors like the following one:

  In file included from ISOBMFF/include/ISOBMFF/Box.hpp:36:
  ISOBMFF/include/ISOBMFF/BinaryStream.hpp:34:10: fatal error: 'string' file not found
  #include <string>
           ^~~~~~~~
  1 error generated.
  make[1]: *** [Submodules/makelib/Targets.mk:219: Build/Release/Intermediates/x86_64/IPCO.cpp.o] Error 1